<a href="https://colab.research.google.com/github/Gaurangvasiyar/new_demo1/blob/main/salary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
reg=linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [11]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [12]:
reg.predict([[2500, 4, 5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [47]:
new_df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/hiring.csv')
new_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [48]:
string_to_number = {
    'zero': 0,
    'one': 1,
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5,
    'six': 6,
    'seven': 7,
    'eight': 8,
    'nine': 9,
    'ten': 10,
    'eleven':11
}

In [52]:
new_df['experience'] = new_df['experience'].replace(string_to_number)
new_df.experience

0     NaN
1     NaN
2     5.0
3     2.0
4     7.0
5     3.0
6    10.0
7    11.0
Name: experience, dtype: float64

In [56]:
new_df['test_score(out of 10)']=new_df['test_score(out of 10)'].fillna(new_df['test_score(out of 10)'].median())
new_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [57]:
new_df['experience']=new_df['experience'].fillna(new_df['experience'].median())
new_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [58]:
new_reg=linear_model.LinearRegression()
new_reg.fit(new_df.drop('salary($)',axis='columns'),new_df['salary($)'])

LinearRegression()

In [59]:
new_reg.predict([[2, 9, 6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([47056.91056911])

In [60]:
new_reg.predict([[12, 10, 10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([88227.64227642])

In [62]:
new_reg.coef_


array([2813.00813008, 1333.33333333, 2926.82926829])

In [63]:
new_reg.intercept_


11869.91869918695

In [64]:
2813.00813008*12 + 1333.33333333*10 + 2926.82926829*10 + 11869.91869918695

88227.64227634695